stages:
  - tests

.rust-template: &rust-template
  before_script:
    - rustup --version
    - rustc --version
    - cargo --version
  tags:
    - speedy

tests:
  image: 'registry.mattr.network/devops/images/rust_build'
  <<: *rust-template
  stage: tests
  script:
    - cd honggfuzz && NUM_JOBS=32 cargo hfuzz run fuzz_target_compare
  only:
    - master
