[package]
name = "eth_pairings"
version = "0.4.0"
authors = ["Alex Vlasov <alex.m.vlasov@gmail.com>"]
edition = "2018"
description = "EIP1962 reference implementation"
homepage = "https://github.com/matter-labs/eip1962"
license = "Apache-2.0"
exclude = [
    "fuzz",
    "honggfuzz",
    "*.sh",
    "src/test",
    "cpp_version"
]

[lib]
name = "eth_pairings"
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
byteorder = "1.3"
eth_pairings_repr_derive = {version = "0.2.0", path = "repr_derive"}
fixed_width_field = {version = "0.1", path = "fixed_width_field" }
fixed_width_fp3_fp4 = {version = "0.1", path = "fixed_width_fp3_fp4" }
fixed_width_fp6 = {version = "0.1", path = "fixed_width_fp6" }
fixed_width_fp12 = {version = "0.1", path = "fixed_width_fp12" }
fixed_width_group_and_loop = {version = "0.1", path = "fixed_width_group_and_loop" }
static_assertions = "1.1.*"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = {version = "1.0", optional = true }
once_cell = {version = "1.*", optional = true }

[dev-dependencies]
num-bigint = "0.2"
num-traits = "0.2"
num-integer = "0.1"
hex = "0.4"
rand = "0.7"
rand_xorshift = "0.2"
csv = "1"
pbr = "*"

rayon = "1.*"
indicatif = {version = "*", features = ["with_rayon"]}

[features]
benchmarks = []
gas_metering = ["serde", "serde_json", "once_cell"]

[profile.dev]
incremental = false

[profile.test]
incremental = false

[profile.release]
incremental = false

[profile.bench]
incremental = false