[package]
name = "eth_pairings"
version = "0.1.1"
authors = ["Alex Vlasov <alex.m.vlasov@gmail.com>"]
edition = "2018"
description = "EIP1962 reference implementation"
homepage = "https://github.com/matter-labs/eip1962"
license = "Apache-2.0"
exclude = [
    "repr_derive",
    "fuzz",
    "honggfuzz",
    "*.sh",
    "src/test"
]

[dependencies]
byteorder = "1.3"
eth_pairings_repr_derive = {version = "0.1.0", path = "repr_derive"}
num-bigint = "0.2"
num-traits = "0.2"
num-integer = "0.1"
lazy_static = "1.3.0"

[dev-dependencies]
hex = "0.3.2"
rand = "0.6.5"
rand_xorshift = "0.1.1"
csv = "1"
#criterion = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
benchmarks = []
gas_metering = []